### ISSUE TITLE
Karma unit test - Failed: Cannot read property 'initialise' of undefined

### ISSUE THREAD

**Issue by Ismaestro** [tinesoft/ngx-cookieconsent#30]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Mojave

### Versions

Angular CLI: 6.2.7
Node: 8.11.2
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.4
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.8.4
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               0.8.4
@angular-devkit/schematics         0.8.7
@angular/cdk                       6.4.7
@angular/cli                       6.2.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                0.8.7
@schematics/update                 0.8.7
ng-packagr                         4.2.0
rxjs                               6.3.3
typescript                         2.7.2
webpack                            4.19.1

### Repro steps

I have included the library following the steps without any problem, but when I try to make a unit test the following error ocurs:

My test is:
```
const cookieConfig: NgcCookieConsentConfig = {
  cookie: {
    domain: 'localhost'
  }
};
fdescribe('HeaderComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        ...
        NgcCookieConsentModule.forRoot(cookieConfig)],
      providers: [
        ...
        {provide: APP_BASE_HREF, useValue: '/'}
      ]
    });
  });

  it('should create the app', async(() => {
    const fixture = TestBed.createComponent(HeaderComponent);
    const app = fixture.debugElement.componentInstance;
    expect(app).toBeTruthy();
  }));
});
```
### The log given by the failure

Failed: Cannot read property 'initialise' of undefined
        error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33669121, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 114688, directChildFlags: 114688, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'app-header', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 114688, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex: -1, childCount: 0, bindings: Array, bindingFlags: 0, outputs: Array ...
at <Jasmine>
            at NgcCookieConsentService.push../node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js.NgcCookieConsentService.init (http://localhost:9876/node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js?:149:1)
            at new NgcCookieConsentService (http://localhost:9876/node_modules/ngx-cookieconsent/esm5/ngx-cookieconsent.es5.js?:96:1)

### Desired functionality

The usecase is just load the service in the OnInit method and use it...

**Comment by tinesoft** [comment]
Hi,

You need to instruct **Karma** to load the `cookieconsent` global library by refering it in your `karma.config.js `.

Take a look at this [karma.config.js](https://github.com/tinesoft/ngx-cookieconsent/blob/5f2ba0eea33f2ac517c52b59945d998c9321b806/config/karma.conf.js#L26)

**Comment by atropo** [comment]
Hi, got the same problem but I'm using `jest` and not `jasmine/karma`. The application works fine, only the unit test fails:


### OS and Version?
Linux

### Versions
Angular CLI: 9.1.0
Node: 12.16.1
OS: linux x64
jest: 25.3.0

### Package Versions
"cookieconsent": "^3.1.1",
"ngx-cookieconsent": "^2.2.3"





### The log

```js
TypeError: Cannot read property 'initialise' of undefined

      at NgcCookieConsentService.Object.<anonymous>.NgcCookieConsentService.init (node_modules/tmp/service/cookieconsent.service.ts:162:26)
      at new NgcCookieConsentService (node_modules/tmp/service/cookieconsent.service.ts:119:10)
      at _createClass (../packages/core/src/view/ng_module.ts:178:14)
      at _createProviderInstance (../packages/core/src/view/ng_module.ts:146:20)
      at resolveNgModuleDep (../packages/core/src/view/ng_module.ts:107:13)
      at NgModuleRef_.Object.<anonymous>.NgModuleRef_.get (../packages/core/src/view/refs.ts:390:12)
      at resolveDep (../packages/core/src/view/provider.ts:418:43)
      at createClass (../packages/core/src/view/provider.ts:269:23)
      at createDirectiveInstance (../packages/core/src/view/provider.ts:135:20)
      at createViewNodes (../packages/core/src/view/view.ts:303:28)
      at createRootView (../packages/core/src/view/view.ts:210:3)
      at callWithDebugContext (../packages/core/src/view/services.ts:629:23)
      at Object.debugCreateRootView [as createRootView] (../packages/core/src/view/services.ts:121:10)
      at ComponentFactory_.Object.<anonymous>.ComponentFactory_.create (../packages/core/src/view/refs.ts:92:27)
      at initComponent (../../packages/core/testing/src/test_bed.ts:612:28)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Object.onInvoke (../packages/core/src/zone/ng_zone.ts:302:25)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
      at NgZone.Object.<anonymous>.NgZone.run (../packages/core/src/zone/ng_zone.ts:178:50)
      at TestBedViewEngine.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:616:56)
      at Function.Object.<anonymous>.TestBedViewEngine.createComponent (../../packages/core/testing/src/test_bed.ts:241:36)
      at src/app/app.component.spec.ts:44:29
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:386:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:117:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:385:36)
      at Zone.Object.<anonymous>.Zone.run (node_modules/zone.js/dist/zone.js:143:47)
```


###  Mention any other details that might be useful

I've added the `cookieConsent` files to `ts.config.spec.json`, but still got the error.

```js
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": [
      "jasmine",
      "node",
      "jest"
    ],
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "allowJs": true
  },
  "files": [
    "src/polyfills.ts",
    "node_modules/cookieconsent/build/cookieconsent.min.js",
    "node_modules/cookieconsent/build/cookieconsent.min.css"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```

**Comment by tinesoft** [comment]
@atropo  Same solution as for Karma:

As described in the [jest-preset-angular](https://github.com/thymikee/jest-preset-angular#allow-vendor-libraries-like-jquery-etc) page, you must import the global library `coockieconsent` in your Jest `setupJest.ts` file , like so:

```
import 'cookieconsent';
global.cookieconsent = cookieconsent;
```
